#
# Table structure for table `members`
#

CREATE TABLE `members` (
  `member_id` int(11) unsigned NOT NULL auto_increment,
  `firstname` varchar(100) default NULL,
  `lastname` varchar(100) default NULL,
  `login` varchar(100) NOT NULL default ``,
  `passwd` varchar(32) NOT NULL default ``,
  PRIMARY KEY  (`member_id`)
) TYPE=MyISAM;



#
# Dumping data for table `members`
#

INSERT INTO `members` (`member_id`, `firstname`, `lastname`, `login`, `passwd`) VALUES("1", "Jatinder", "Thind", "phpsense", "ba018360fc26e0cc2e929b8e071f052d");

#
#Table structure for `AASC_Inventory`
#
CREATE TABLE `AASC_Inventory` (
 `ClientAccountNumber`  varchar(25) not null,
 `VIN` varchar(17),
 `AuctionID` varchar(4),
 `PickupDate` date,
 `DropOffDate` date,
 `DeleteCancelRequest` varchar(6),
 `SecondaryClient` varchar(50),
 `ModelYear` int(4),
 `Make` varchar(30),
 `Model` varchar(30),
 `Series` varchar(30),
 `BodyStyle` varchar(4),
 `ExteriorColor` varchar(20),
 `Classification` int(3),
 `InteriorColor` varchar(20),
 `ClientField1` varchar(35),
 `ClientField2` varchar(35),
 `DriversName` varchar(50),
 `ReplacementVehicleNumber` varchar(25),
 `ReplacementVehicleModelYear` int(4),
 `ReplacementVehicleColor` varchar(20),
 `PayoutAmount` decimal(8,2),
 `LocationType` int(3),
 `LocationName` varchar(50),
 `LocationAddress1` varchar(50),
 `LocationAddress2` varchar(50),
 `LocationCity` varchar(50),
 `LocationState` varchar(20),
 `LocationZip` varchar(20),
 `ContactPerson1` varchar(50),
 `ContactPerson2` varchar(50),
 `Phone1` varchar(30),
 `Phone2` varchar(30),
 `Fax1` varchar(30),
 `Fax2` varchar(30),
 `Email1` varchar(60),
 `Email2` varchar(60),
 `LegalSaleDate` date,
 `HoldStatus` int(3),
 `HoldUntil` date,
 `VehicleIsOperable` int(1),
 `PickupOrDropOffNote` varchar(255),
 `FloorPrice` decimal(8,2),
 `ClientWorkStatus` varchar(2),
 `ClearVehicleForSale` date,
 `RedeemVehicle` date,
 `TitleSent` date,
 `RequestedRunOrder` int(4),
 `FundsReceived` date,
 `ReplacementVehicleMake` varchar(30),
 `ReplacementVehicleModel` varchar(30),
 `TitleShipmentMethod` varchar(1),
 `TitleShipmentTrackingNumber` varchar(15),
 `ClientInternetSellingSuggestion` varchar(1),
 `SendNotificationsToEmail1` varchar(1),
 `SendNotificationsToEmail2` varchar(1),
 `PrivateBookValue` decimal(7,2),
 `PrivateComment1` varchar(50),
 `PrivateComment2` varchar(50),
 `PrivateAmount1` decimal(7,2),
 `PrivateAmount2` decimal(7,2),
 `PrivateDate1` date,
 `PrivateDate2` date,
 `PrivateCode1` varchar(15),
 `PrivateCode2` varchar(15),
 `TransportationMethod` int(2),
 `TransportationCompany` varchar(30),
 `AccountType` varchar(10),
 `PrivateFloorPrice` decimal(7,2),
 `VehicleType` int(3),
 `VehicleKeyCode` varchar(5),
 `VehicleContact` varchar(20),
 `TrueMileageUnknown` int(1),
 `TrueMileageUnknownReason` varchar(30),
 `ExcessWearAndUseClient` decimal(7,2),
 `CleaningLevelRequested` int(2),
 `ManagedMaintenanceProgram` int(1),
 `WarrantyExpirationDate` date,
 `WarrantyExpirationMileage` int(7),
 `WarrantyProvider` varchar(50),
 `ClientDate1` date,
 `ClientDate2` date,
 `ActualCashValue` decimal(7,2),
 `CauseOfClaim` int(3),
 `DateOfLoss` date,
 `AdjusterName` varchar(50),
 `AdjustPhone` varchar(40),
 `DamageAmount` decimal(7,2),
 `TransportLoadID` varchar(12),
 `AuctionBusinessUnit` varchar(2),
 `ReservedIT` varchar(15),
 `ReservedCT` varchar(15),
 `LicensePlate` varchar(10),
 `SubSeries` varchar(20),
 `ClientAmount1` decimal(7,2),
 `OnlinePricingDate` date,
 `OnlinePricingBy` varchar(50),
 `AlternateClientUniqueID` varchar(25),
 `OnlineFixedPrice` decimal(7,2),
 `OnlineStartingBid` decimal(7,2),
 `OnlineBidIncrement` decimal(7,2),
 `OnlineFloorPrice` decimal(7,2),
 `MarshalVehicle` int(1),
 `CRRequested_Marshal` int(1),
 `MarshalingPurpose` varchar(50),
 `MarshaledVehicleReleaseInstructions` varchar(200),
 `ClientAmount2` decimal(7,2),
 `ClientAmount3` decimal(7,2),
 `ClientAmount4` decimal(7,2),
 `ClientAmount5` decimal(7,2),
 `ClientAmount6` decimal(7,2),
 `CC_ID` int(9)
 )
 
 insert into aasc_inventory
 (
 `ClientAccountNumber`,
 `VIN`,
 `AuctionID`,
 `PickupDate` ,
 `DropOffDate` ,
 `DeleteCancelRequest`,
 `SecondaryClient` ,
 `ModelYear` ,
 `Make` ,
 `Model` ,
 `Series` ,
 `BodyStyle` ,
 `ExteriorColor` ,
 `Classification` ,
 `InteriorColor` ,
 `ClientField1` ,
 `ClientField2` ,
 `DriversName` ,
 `ReplacementVehicleNumber` ,
 `ReplacementVehicleModelYear` ,
 `ReplacementVehicleColor` ,
 `PayoutAmount` ,
 `LocationType` ,
 `LocationName` ,
 `LocationAddress1` ,
 `LocationAddress2` ,
 `LocationCity` ,
 `LocationState` ,
 `LocationZip` ,
 `ContactPerson1` ,
 `ContactPerson2` ,
 `Phone1` ,
 `Phone2` ,
 `Fax1` ,
 `Fax2` ,
 `Email1` ,
 `Email2` ,
 `LegalSaleDate` ,
 `HoldStatus` ,
 `HoldUntil` ,
 `VehicleIsOperable` ,
 `PickupOrDropOffNote` ,
 `FloorPrice` ,
 `ClientWorkStatus` ,
 `ClearVehicleForSale` ,
 `RedeemVehicle` ,
 `TitleSent` ,
 `RequestedRunOrder` ,
 `FundsReceived` ,
 `ReplacementVehicleMake` ,
 `ReplacementVehicleModel` ,
 `TitleShipmentMethod` ,
 `TitleShipmentTrackingNumber` ,
 `ClientInternetSellingSuggestion` ,
 `SendNotificationsToEmail1` ,
 `SendNotificationsToEmail2` ,
 `PrivateBookValue` ,
 `PrivateComment1` ,
 `PrivateComment2` ,
 `PrivateAmount1` ,
 `PrivateAmount2` ,
 `PrivateDate1` ,
 `PrivateDate2` ,
 `PrivateCode1` ,
 `PrivateCode2` ,
 `TransportationMethod` ,
 `TransportationCompany` ,
 `AccountType` ,
 `PrivateFloorPrice` ,
 `VehicleType` ,
 `VehicleKeyCode` ,
 `VehicleContact` ,
 `TrueMileageUnknown` ,
 `TrueMileageUnknownReason` ,
 `ExcessWearAndUseClient` ,
 `CleaningLevelRequested` ,
 `ManagedMaintenanceProgram` ,
 `WarrantyExpirationDate` ,
 `WarrantyExpirationMileage` ,
 `WarrantyProvider` ,
 `ClientDate1` ,
 `ClientDate2` ,
 `ActualCashValue` ,
 `CauseOfClaim` ,
 `DateOfLoss` ,
 `AdjusterName` ,
 `AdjustPhone` ,
 `DamageAmount` ,
 `TransportLoadID` ,
 `AuctionBusinessUnit` ,
 `ReservedIT` ,
 `ReservedCT` ,
 `LicensePlate` ,
 `SubSeries` ,
 `ClientAmount1` ,
 `OnlinePricingDate` ,
 `OnlinePricingBy` ,
 `AlternateClientUniqueID` ,
 `OnlineFixedPrice` ,
 `OnlineStartingBid` ,
 `OnlineBidIncrement` ,
 `OnlineFloorPrice` ,
 `MarshalVehicle` ,
 `CRRequested_Marshal` ,
 `MarshalingPurpose` ,
 `MarshaledVehicleReleaseInstructions` ,
 `ClientAmount2` ,
 `ClientAmount3` ,
 `ClientAmount4` ,
 `ClientAmount5` ,
 `ClientAmount6` ,
 `CC_ID` 
 )